apiVersion: v1
kind: Service
metadata:
  name: demo-load-balancer
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30002
  type: LoadBalancer
