apiVersion: v1
kind: Service
metadata:
  name: demo-load-balancer
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080
      nodePort: 30002
  type: LoadBalancer
externalIPS:
- 127.0.0.1
