apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
    - protocol: TCP
      port: 8088
      target: 8888
  selector:
    app: demo
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1
